Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.10/site.py", line 636, in <module>
    main()
  File "/usr/lib/python3.10/site.py", line 623, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/lib/python3.10/site.py", line 406, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.10/site.py", line 232, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.10/site.py", line 192, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap>", line 556, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 397, in cached
  File "<frozen importlib._bootstrap_external>", line 513, in _get_cached
  File "<frozen importlib._bootstrap_external>", line 406, in cache_from_source
  File "<frozen importlib._bootstrap_external>", line 134, in _path_split
  File "<frozen importlib._bootstrap_external>", line 134, in <genexpr>
KeyboardInterrupt
gmake[2]: *** [CMakeFiles/ament_cmake_python_build_tku_msgs_egg.dir/build.make:70: CMakeFiles/ament_cmake_python_build_tku_msgs_egg] Interrupt
gmake[1]: *** [CMakeFiles/Makefile2:447: CMakeFiles/ament_cmake_python_build_tku_msgs_egg.dir/all] Interrupt
gmake: *** [Makefile:146: all] Interrupt
